name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, curl, xml

    - name: Install dependencies
      run: |
        composer install --no-interaction

    - name: Run tests
      run: |
        vendor/bin/phpunit --configuration phpunit.xml

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Start ssh-agent and add SSH key
      run: |
        eval "$(ssh-agent -s)"  # Start the SSH agent
        echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa  # Add the private key with the passphrase

    - name: Deploy to O2switch
      env:
        PASSWORD: ${{ secrets.O2SWITCH_PASSWORD }}
      run: |
        sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no rame5605@109.234.166.50 "cd /home/rame5605/api.herbeginfos.fr && git pull origin main && composer install --no-dev"