name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, curl, xml

    - name: Install dependencies
      run: |
        composer install --no-interaction

    - name: Run tests
      run: |
        vendor/bin/phpunit --configuration phpunit.xml

    # - name: Run PHPStan
    #   run: |
    #     vendor/bin/phpstan analyse app --level=max

    # - name: Check connectivity
    #   run: |
    #     ping -c 4 109.234.166.50

    - name: Display GitHub Actions IP information
      run: |
        echo "Displaying GitHub Actions IP ranges information:"
        echo "Current runner IP: $(curl -s https://api.ipify.org)"
        echo "GitHub Actions IP ranges:"
        curl -s https://api.github.com/meta | jq -r '.actions[]'
        echo "These IPs need to be allowed in your O2switch SSH configuration"

    - name: Create .ssh directory
      run: |
        mkdir -p $HOME/.ssh
        echo "Directory created: $HOME/.ssh"

    - name: Check host connectivity
      continue-on-error: true
      run: |
        echo "Checking connectivity to deployment server..."
        if ping -c 2 -W 5 109.234.166.50 &>/dev/null; then
          echo "Host is reachable via ping"
        else
          echo "Warning: Host not responding to ping (this might be normal if ICMP is blocked)"
        fi
        
        if nc -z -w 5 109.234.166.50 22 &>/dev/null; then
          echo "SSH port is open and accessible"
        else
          echo "Warning: SSH port seems closed or filtered"
        fi

    - name: Add SSH host to known_hosts
      continue-on-error: true
      run: |
        echo "Attempting to scan SSH host key..."
        for i in {1..3}; do
          echo "Attempt $i to scan host key..."
          if ssh-keyscan -v -T 10 -H 109.234.166.50 >> $HOME/.ssh/known_hosts 2>&1; then
            echo "SSH host key successfully added to known_hosts."
            exit 0
          else
            echo "Attempt $i failed. Waiting before retry..."
            sleep 5
          fi
        done
        echo "Failed to scan host key after multiple attempts. Continuing anyway..."
        # Manually adding a placeholder to avoid host key verification in the deployment step
        echo "109.234.166.50 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA..." >> $HOME/.ssh/known_hosts

    - name: Set up SSH key
      run: |
        # Make sure the SSH key is properly formatted (base64 encoded keys might need decoding)
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        
        # Start ssh-agent
        eval "$(ssh-agent -s)"
        
        # Add key to agent - since there's no passphrase or it's empty, this should work
        ssh-add $HOME/.ssh/id_rsa
        
        # Verify the key was added correctly
        ssh-add -l
        
        # Check the beginning of the key for debugging (don't display the whole key)
        echo "Key starts with: $(head -n 1 $HOME/.ssh/id_rsa)"

    - name: Deploy to O2switch
      run: |
        # Try alternative connection approaches
        echo "Attempting SSH connection with various options..."
        ssh -vvv -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 rame5605@109.234.166.50 "echo 'Connection successful'" || true
        
        # Now try the actual deployment command
        ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 rame5605@109.234.166.50 "cd /home/rame5605/api.herbeginfos.fr && git pull origin main && composer install --no-dev" || {
          echo "==================================================="
          echo "Deployment failed. Common causes include:"
          echo "1. IP restrictions on the server (O2switch may block GitHub Actions IPs)"
          echo "2. SSH key format issues (make sure it's in OpenSSH format)"
          echo "3. Server configuration not accepting the key"
          echo "Consider using SFTP deployment or asking O2switch support about CI/CD deployments"
          echo "==================================================="
          exit 1
        }
