name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, curl, xml

    - name: Install dependencies
      run: |
        composer install --no-interaction

    - name: Run tests
      run: |
        vendor/bin/phpunit --configuration phpunit.xml
      
    # - name: Run PHPStan
    #   run: |
    #     vendor/bin/phpstan analyse app --level=max

    - name: Add SSH host to known_hosts
      run: |
        mkdir -p /home/runner/.ssh
        ssh-keyscan -H 109.234.166.50 >> /home/runner/.ssh/known_hosts

    - name: Set up SSH key
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add /home/runner/.ssh/id_rsa

    - name: Deploy to O2switch
      run: |
        ssh rame5605@109.234.166.50 "cd /home/rame5605/api.herbeginfos.fr && git pull origin main && composer install --no-dev"