name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, curl, xml

    - name: Install dependencies
      run: |
        composer install --no-interaction

    - name: Run tests
      run: |
        vendor/bin/phpunit --configuration phpunit.xml

    # - name: Run PHPStan
    #   run: |
    #     vendor/bin/phpstan analyse app --level=max

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Charge la clé privée du secret GitHub

    - name: Add passphrase to SSH key
      run: |
        echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add -K ~/.ssh/id_rsa  # Ajoute la passphrase via un secret

    - name: Deploy to O2switch
      run: |
        ssh -o StrictHostKeyChecking=no rame5605@109.234.166.50 "cd /home/rame5605/api.herbeginfos.fr && git pull origin main && composer install --no-dev"