name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, curl, xml

    - name: Install dependencies
      run: |
        composer install --no-interaction

    - name: Run tests
      run: |
        vendor/bin/phpunit --configuration phpunit.xml

    # - name: Run PHPStan
    #   run: |
    #     vendor/bin/phpstan analyse app --level=max

    # - name: Check connectivity
    #   run: |
    #     ping -c 4 109.234.166.50

    - name: Create .ssh directory
      run: |
        mkdir -p $HOME/.ssh
        echo "Directory created: $HOME/.ssh"

    - name: Check host connectivity
      run: |
        echo "Checking connectivity to deployment server..."
        if ping -c 2 -W 5 109.234.166.50 &>/dev/null; then
          echo "Host is reachable via ping"
        else
          echo "Warning: Host not responding to ping (this might be normal if ICMP is blocked)"
        fi
        
        if nc -z -w 5 109.234.166.50 22 &>/dev/null; then
          echo "SSH port is open and accessible"
        else
          echo "Warning: SSH port seems closed or filtered"
        fi

    - name: Add SSH host to known_hosts
      run: |
        echo "Attempting to scan SSH host key..."
        for i in {1..3}; do
          echo "Attempt $i to scan host key..."
          if ssh-keyscan -v -T 10 -H 109.234.166.50 >> $HOME/.ssh/known_hosts 2>&1; then
            echo "SSH host key successfully added to known_hosts."
            exit 0
          else
            echo "Attempt $i failed. Waiting before retry..."
            sleep 5
          fi
        done
        echo "Failed to scan host key after multiple attempts. Continuing anyway..."
        # Don't fail the workflow, we'll let the actual SSH connection attempt determine success

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add $HOME/.ssh/id_rsa

    - name: Deploy to O2switch
      run: |
        ssh -v rame5605@109.234.166.50 "cd /home/rame5605/api.herbeginfos.fr && git pull origin main && composer install --no-dev"
