name: CI

on:
  push:
    branches:
      - main  # Ou la branche principale de ton projet
  pull_request:
    branches:
      - main  # Ou la branche principale de ton projet

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Choisir la version de PHP que tu utilises
        extensions: mbstring, bcmath, curl, xml  # Extensions PHP nécessaires

    - name: Install dependencies
      run: |
        composer install --no-interaction

    - name: Run tests
      run: |
        vendor/bin/phpunit --configuration phpunit.xml
        
    - name: Deploy to O2switch
      run: |
        ssh rame5605@109.234.166.50 "cd /home/rame5605/api.herbeginfos.fr && git pull origin main && composer install --no-dev"