name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, curl, xml

    - name: Install dependencies
      run: |
        composer install --no-interaction

    - name: Run tests
      run: |
        vendor/bin/phpunit --configuration phpunit.xml

    # - name: Run PHPStan
    #   run: |
    #     vendor/bin/phpstan analyse app --level=max

    - name: Deploy to O2switch via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: choucas.o2switch.net
        username: rame5605
        password: Y6ht-DAqD-QD3)
        local-dir: ./build
        server-dir: /home/rame5605/api.herbeginfos.fr
        